//This code was generated by MS-Builder
package com.amdocs.digital.ms.shoppingcart.checkout.couchbase.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;


/**
 * Configuration class for the Repository layer.
 */
@Configuration
public class RepositoriesConfig {
	

}
