//This code was generated by MS-Builder
package com.amdocs.digital.ms.shoppingcart.checkout.resources.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Delegates configuration file.
 */
@Configuration
public class ResourceLayerConfig 
{
}