//This code was generated by MS-Builder
package com.amdocs.digital.ms.shoppingcart.checkout.resources.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.amdocs.digital.ms.shoppingcart.checkout.resources.mappers.interfaces.*;
import com.amdocs.digital.ms.shoppingcart.checkout.resources.mappers.implementation.*;

/**
 * Mappers configuration file.
 */
@Configuration
public class ResourceMappersConfig {


 	@Bean
    public  IPopulateHrefs populateHrefs() {
        return new PopulateHrefs();
    }
}