//This code was generated by MS-Builder
package com.amdocs.digital.ms.shoppingcart.checkout.business.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Application services configuration file.
 */
@Configuration
public class ApplicationServicesConfig 
{	
}
