//This code was generated by MS-Builder
package com.amdocs.digital.ms.shoppingcart.checkout.gateways.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;


/**
 * Gateways services configuration file.
 */
@Configuration
public class GatewayApplicationServiceConfig {
	 
}
